apiVersion: v1
kind: ConfigMap
metadata:
  name: finops-api-config
  namespace: finops
data:
  OPENCOST_URL: "http://opencost.opencost.svc.cluster.local:9003"
  VM_URL: "http://vmsingle-vmks-victoria-metrics-k8s-stack.vmks.svc.cluster.local:8428"
  YC_REGION: "ru-central1"
  YC_ENDPOINT: "https://storage.yandexcloud.net"
  YC_BUCKET: "finops-billing"
