apiVersion: apps/v1
kind: Deployment
metadata:
  name: finops-api
  namespace: finops
  labels:
    app: finops-api
    team: platform
    env: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finops-api
  template:
    metadata:
      labels:
        app: finops-api
        team: platform
        env: production
    spec:
      containers:
        - name: api
          image: cr.yandex/crppm2p2j5q3tmf17su4/finops-api:
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: finops-api-config
            - secretRef:
                name: finops-api-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
