apiVersion: apps/v1
kind: Deployment
metadata:
  name: finops-frontend
  namespace: finops
  labels:
    app: finops-frontend
    team: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finops-frontend
  template:
    metadata:
      labels:
        app: finops-frontend
        team: platform
    spec:
      containers:
        - name: finops-frontend
          image: cr.yandex/YOUR_REGISTRY_ID/finops-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
