apiVersion: apps/v1
kind: Deployment
metadata:
  name: finops-frontend
  namespace: finops
  labels:
    app: finops-frontend
    team: platform
    env: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finops-frontend
  template:
    metadata:
      labels:
        app: finops-frontend
        team: platform
        env: production
    spec:
      containers:
        - name: frontend
          image: cr.yandex/crppm2p2j5q3tmf17su4/finops-frontend:790d353
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
