apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: opencost-metrics
  namespace: opencost
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: opencost
  namespaceSelector:
    matchNames:
      - opencost
  endpoints:
    - port: http
      path: /metrics
      interval: 60s
