apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: finops
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
  clusterIP: None
