apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finops-api
  namespace: argocd
  labels:
    team: platform
spec:
  project: default
  source:
    repoURL: https://github.com/mityay36/finops-mvp
    targetRevision: main
    path: k8s/api
  destination:
    server: https://kubernetes.default.svc
    namespace: finops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image  # управляется CI/CD
