---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vmks
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/mityay36/finops-mvp
      targetRevision: main
      ref: gitrepo
    - repoURL: ghcr.io/victoriametrics/helm-charts
      chart: victoria-metrics-k8s-stack
      targetRevision: 0.72.6
      helm:
        releaseName: vmks
        valueFiles:
          - $gitrepo/k8s/vmks/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vmks
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - Validate=false
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: vmks-victoria-metrics-operator-validation
      namespace: vmks
      jsonPointers:
        - /data
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: vmks-victoria-metrics-operator-admission
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
    - kind: Secret
      jsonPointers:
        - /data/admin-password
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
