"""initial schema

Revision ID: 304695b88279
Revises: 
Create Date: 2026-05-14 21:23:57.161240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '304695b88279'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider_type', sa.Enum('yc', 'onprem', name='provider_type_enum'), nullable=False),
    sa.Column('opencost_url', sa.String(length=512), nullable=False),
    sa.Column('vm_url', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cluster_profiles')),
    sa.UniqueConstraint('name', name='uq_cluster_profiles_name')
    )
    op.create_table('billing_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('resource_name', sa.String(length=512), nullable=False),
    sa.Column('sku_name', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=16), server_default='RUB', nullable=False),
    sa.Column('label_namespace', sa.String(length=255), nullable=True),
    sa.Column('label_service', sa.String(length=255), nullable=True),
    sa.Column('is_preemptible', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster_profiles.id'], name=op.f('fk_billing_records_cluster_id_cluster_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_records')),
    sa.UniqueConstraint('cluster_id', 'period_start', 'resource_id', 'sku_name', name='uq_billing_records_cluster_period_resource_sku')
    )
    op.create_index(op.f('ix_billing_records_cluster_id'), 'billing_records', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_billing_records_label_namespace'), 'billing_records', ['label_namespace'], unique=False)
    op.create_index(op.f('ix_billing_records_label_service'), 'billing_records', ['label_service'], unique=False)
    op.create_index(op.f('ix_billing_records_period_start'), 'billing_records', ['period_start'], unique=False)
    op.create_index(op.f('ix_billing_records_resource_id'), 'billing_records', ['resource_id'], unique=False)
    op.create_index(op.f('ix_billing_records_service_name'), 'billing_records', ['service_name'], unique=False)
    op.create_table('billing_sync_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='sync_run_status_enum'), server_default='running', nullable=False),
    sa.Column('records_imported', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster_profiles.id'], name=op.f('fk_billing_sync_runs_cluster_id_cluster_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_sync_runs'))
    )
    op.create_index(op.f('ix_billing_sync_runs_cluster_id'), 'billing_sync_runs', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_billing_sync_runs_started_at'), 'billing_sync_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_billing_sync_runs_status'), 'billing_sync_runs', ['status'], unique=False)
    op.create_table('cost_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('cpu_cost', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False),
    sa.Column('ram_cost', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False),
    sa.Column('pv_cost', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False),
    sa.Column('network_cost', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=6), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster_profiles.id'], name=op.f('fk_cost_snapshots_cluster_id_cluster_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_snapshots')),
    sa.UniqueConstraint('cluster_id', 'snapshot_at', 'namespace', name='uq_cost_snapshots_cluster_snapshot_namespace')
    )
    op.create_index(op.f('ix_cost_snapshots_cluster_id'), 'cost_snapshots', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_cost_snapshots_namespace'), 'cost_snapshots', ['namespace'], unique=False)
    op.create_index(op.f('ix_cost_snapshots_snapshot_at'), 'cost_snapshots', ['snapshot_at'], unique=False)
    op.create_table('onprem_tco_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('hardware_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('amortization_years', sa.Integer(), nullable=False),
    sa.Column('power_watts', sa.Integer(), nullable=False),
    sa.Column('electricity_tariff', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('colocation_monthly', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('cpu_cores_per_node', sa.Integer(), nullable=False),
    sa.Column('ram_gb_per_node', sa.Integer(), nullable=False),
    sa.Column('cpu_to_ram_cost_ratio', sa.Numeric(precision=4, scale=2), server_default='0.70', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster_profiles.id'], name=op.f('fk_onprem_tco_config_cluster_id_cluster_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onprem_tco_config')),
    sa.UniqueConstraint('cluster_id', name='uq_onprem_tco_config_cluster_id')
    )
    op.create_index(op.f('ix_onprem_tco_config_cluster_id'), 'onprem_tco_config', ['cluster_id'], unique=False)
    op.create_table('provider_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('key_name', sa.String(length=128), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster_profiles.id'], name=op.f('fk_provider_credentials_cluster_id_cluster_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_credentials')),
    sa.UniqueConstraint('cluster_id', 'key_name', name='uq_provider_credentials_cluster_key_name')
    )
    op.create_index(op.f('ix_provider_credentials_cluster_id'), 'provider_credentials', ['cluster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_credentials_cluster_id'), table_name='provider_credentials')
    op.drop_table('provider_credentials')
    op.drop_index(op.f('ix_onprem_tco_config_cluster_id'), table_name='onprem_tco_config')
    op.drop_table('onprem_tco_config')
    op.drop_index(op.f('ix_cost_snapshots_snapshot_at'), table_name='cost_snapshots')
    op.drop_index(op.f('ix_cost_snapshots_namespace'), table_name='cost_snapshots')
    op.drop_index(op.f('ix_cost_snapshots_cluster_id'), table_name='cost_snapshots')
    op.drop_table('cost_snapshots')
    op.drop_index(op.f('ix_billing_sync_runs_status'), table_name='billing_sync_runs')
    op.drop_index(op.f('ix_billing_sync_runs_started_at'), table_name='billing_sync_runs')
    op.drop_index(op.f('ix_billing_sync_runs_cluster_id'), table_name='billing_sync_runs')
    op.drop_table('billing_sync_runs')
    op.drop_index(op.f('ix_billing_records_service_name'), table_name='billing_records')
    op.drop_index(op.f('ix_billing_records_resource_id'), table_name='billing_records')
    op.drop_index(op.f('ix_billing_records_period_start'), table_name='billing_records')
    op.drop_index(op.f('ix_billing_records_label_service'), table_name='billing_records')
    op.drop_index(op.f('ix_billing_records_label_namespace'), table_name='billing_records')
    op.drop_index(op.f('ix_billing_records_cluster_id'), table_name='billing_records')
    op.drop_table('billing_records')
    op.drop_table('cluster_profiles')
    # ### end Alembic commands ###
