"""add window columns to billing_sync_runs

Revision ID: 3fcb7b029a1d
Revises: 304695b88279
Create Date: 2026-05-15 00:13:36.522347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fcb7b029a1d'
down_revision: Union[str, Sequence[str], None] = '304695b88279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_sync_runs', sa.Column('window_start', sa.DateTime(timezone=True), nullable=False))
    op.add_column('billing_sync_runs', sa.Column('window_end', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_sync_runs', 'window_end')
    op.drop_column('billing_sync_runs', 'window_start')
    # ### end Alembic commands ###
